/**
 * StoryTime Reader API
 * Interface to the StoryTime Reader service, supporting consumers of stories.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@happyspiritgames.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Destination', 'model/ErrorResponse', 'model/Pong', 'model/Scene', 'model/SearchResults', 'model/StorySummary', 'api/DevelopersApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Destination'), require('./model/ErrorResponse'), require('./model/Pong'), require('./model/Scene'), require('./model/SearchResults'), require('./model/StorySummary'), require('./api/DevelopersApi'));
  }
}(function(ApiClient, Destination, ErrorResponse, Pong, Scene, SearchResults, StorySummary, DevelopersApi) {
  'use strict';

  /**
   * Interface_to_the_StoryTime_Reader_service_supporting_consumers_of_stories_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var StoryTimeReaderApi = require('index'); // See note below*.
   * var xxxSvc = new StoryTimeReaderApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new StoryTimeReaderApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new StoryTimeReaderApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new StoryTimeReaderApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Destination model constructor.
     * @property {module:model/Destination}
     */
    Destination: Destination,
    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse: ErrorResponse,
    /**
     * The Pong model constructor.
     * @property {module:model/Pong}
     */
    Pong: Pong,
    /**
     * The Scene model constructor.
     * @property {module:model/Scene}
     */
    Scene: Scene,
    /**
     * The SearchResults model constructor.
     * @property {module:model/SearchResults}
     */
    SearchResults: SearchResults,
    /**
     * The StorySummary model constructor.
     * @property {module:model/StorySummary}
     */
    StorySummary: StorySummary,
    /**
     * The DevelopersApi service constructor.
     * @property {module:api/DevelopersApi}
     */
    DevelopersApi: DevelopersApi
  };

  return exports;
}));
