/**
 * StoryTime Reader API
 * Interface to the StoryTime Reader service, supporting consumers of stories.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@happyspiritgames.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Destination'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Destination'));
  } else {
    // Browser globals (root is window)
    if (!root.StoryTimeReaderApi) {
      root.StoryTimeReaderApi = {};
    }
    root.StoryTimeReaderApi.Scene = factory(root.StoryTimeReaderApi.ApiClient, root.StoryTimeReaderApi.Destination);
  }
}(this, function(ApiClient, Destination) {
  'use strict';




  /**
   * The Scene model module.
   * @module model/Scene
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Scene</code>.
   * @alias module:model/Scene
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Scene</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Scene} obj Optional instance to populate.
   * @return {module:model/Scene} The populated <code>Scene</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('key')) {
        obj['key'] = ApiClient.convertToType(data['key'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('prose')) {
        obj['prose'] = ApiClient.convertToType(data['prose'], 'String');
      }
      if (data.hasOwnProperty('signPost')) {
        obj['signPost'] = ApiClient.convertToType(data['signPost'], [Destination]);
      }
    }
    return obj;
  }

  /**
   * @member {String} key
   */
  exports.prototype['key'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} prose
   */
  exports.prototype['prose'] = undefined;
  /**
   * @member {Array.<module:model/Destination>} signPost
   */
  exports.prototype['signPost'] = undefined;



  return exports;
}));


